export const BAD_HABIT_ALTERNATIVES = {
  physical: [
    "Take a short walk outside to refresh your mind",
    "Do a quick 5-minute workout or stretch",
    "Stretch your neck, shoulders, and back",
    "Learn or practice a few dance moves",
    "Play with a pet or spend time with an animal",
    "Prepare a healthy snack for later",
    "Try a new hairstyle or grooming routine",
  ],
  mental: [
    "Do a crossword puzzle or brain game",
    "Read a chapter of a book",
    "Learn a new skill on a learning app",
    "Watch a motivational video",
    "Listen to a podcast on a topic that interests you",
    "Plan a dream vacation or weekend getaway",
    "Research and read about a positive role model",
  ],
  relaxation: [
    "Practice deep breathing exercises",
    "Use a guided meditation app",
    "Listen to a calming playlist",
    "Do breathing exercises to reduce stress",
    "Find a cozy spot and read a few pages",
    "Color in a coloring book for relaxation",
    "Doodle or sketch something on a piece of paper",
  ],
  social: [
    "Call or text a friend or family member",
    "Write a thank-you note to someone you appreciate",
    "Reflect on a past accomplishment",
    "Plan a small goal for the day",
    "Play with a pet or spend time with an animal",
    "Start learning a few words in a new language",
    "Write a small poem or a paragraph of free writing",
  ],
};